sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 8.1
    - php: 8.2

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - if [ "$deps" = "high" ]; then composer config minimum-stability dev; fi
  - composer update $COMPOSER_OPTIONS

script:
  - vendor/bin/phpspec run
